version: '3.4'

networks:
  k6:
  grafana:

services:

  mongo-service:
    image: mongo
    expose: 
      - "${DBPORT}"
    command: --port ${DBPORT} --logpath /var/log/mongodb/mongodb.log
    volumes:
      - "datavolume:/data/db"
      - "logsvolume:/var/log/mongodb"
      
  planet-service:
    restart: 'always'
    build:
      context: ./backend
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    depends_on:
      - mongo-service
    volumes:
     - "logsvolume:/usr/src/app/src/logs"
    expose:
      - "${BACK_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACK_PORT}
      - DBPORT=${DBPORT}
      - MONGODB_URI=${MONGODB_URI}
  
  frontend-service:
    restart: 'always'
    build:
      context: ./frontend
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - planet-service
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${FRONT_PORT}
      - REACT_APP_BACK_PORT=${BACK_PORT}
  
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts
      
volumes:

  datavolume:
  logsvolume:
    external: true

