version: '3.4'

services:

  mongo-service:
    image: mongo
    expose: 
      - "${DBPORT}"
    command: --port ${DBPORT} --logpath /var/log/mongodb/mongodb.log
    volumes:
      - "datavolume:/data/db"
      - "logsvolume:/var/log/mongodb"
      
  planet-service:
    restart: 'always'
    build:
      context: ./backend
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    depends_on:
      - mongo-service
    volumes:
     - "logsvolume:/usr/src/app/src/logs"
    expose:
      - "${BACK_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACK_PORT}
      - DBPORT=${DBPORT}
      - MONGODB_URI=${MONGODB_URI}
  
  frontend-service:
    restart: 'always'
    build:
      context: ./frontend
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - planet-service
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${FRONT_PORT}
      - REACT_APP_BACK_PORT=${BACK_PORT}
  
volumes:
  
  datavolume:
  logsvolume:
    external: true