apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: bujosa/do2122-c07
    context: ./backend
  - image: bujosa/do2122-c07-frontend
    context: ./frontend
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - k8s.yaml