openapi: 3.0.0
info:
  version: 1.0.0
  title: Planet list
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: PabloFM
    email: pablofm@us.es
    url: 'http://www.isa.us.es'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/planets:
    get:
      description: Returns all planets
      operationId: getPlanets
      responses:
        '200':
          description: Planet List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/planet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    post:
      description: Creates a new planet
      operationId: addPlanet
      responses:
        '201':
          description: planet created
        '422':
          description: planet is not well-formed
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: planet
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/planet'
        description: Planet to be created
        required: true
  '/api/v1/planets/{name}':
    get:
      description: Returns a planet by name
      operationId: findPlanetByname
      parameters:
        - name: name
          in: path
          description: name of planet to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Planet returned
        '400': 
          description: bad request 
        '404':
          description: Planet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/planet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    delete: 
      description: deletes a single planet based on the name
      operationId: deletePlanet
      parameters:
        - name: name
          in: path
          description: ID of planet to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: planet deleted
        '400':
          description: bad request
        '404':
          description: planet not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    put:
      description: Update a planet based on its name
      operationId: updatePlanet
      parameters:
        - name: name
          in: path
          description: ID of planet to put
          required: true
          schema:
            type: string
      responses:
        '204':
          description: planet updated
        '404':
          description: planet not found
        '400':
          description: bad request
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: planet
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/planet'
        description: Planet to be updated
        required: true
  '/api/v1/planets/analytics/{limit}':
    get:
      description: Returns an analytic of the planets registered in the system.
      operationId: analytics
      parameters:
        - name: limit
          in: path
          description: limit of planet to fetch
          required: true
          schema:
            type: number
      responses:
        '200':
          description: analytic returned
        '400': 
          description: bad request 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/analytic'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    planet:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        satellite:
          type: number
        orbitalPeriod:
          type: number
        haveWater:
          type: boolean
        picture:
          type: string
          minLength: 1
      required:
        - name
        - satellite
        - orbitalPeriod
        - haveWater
        - picture
    analytic:
      type: object
      properties:
        haveWater:
          type: number
        dontHaveWater:
          type: number
        satelliteAvg:
          type: number
        orbitalPeriodAvg:
          type: number

