name: IntegrationTest CI

on: 
  push:
    paths:
    - 'backend/**'
    branches:
      - 'main'

jobs: 
  integrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Start Project
        working-directory: ./backend
        run: npm start &
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Use newman to run tests
        working-directory: ./backend
        run: npx newman run ./test/api.json --env-var "baseUrl=http://localhost:8080"